### ISSUE TITLE
add_battleScreens_to_xcode

### ISSUE THREAD

**Issue by alekhyaku** [jcderry5/step-strikers#20]
This Issue contains 6 Battle Screens
Battle - Your Turn - Action
Battle - Your Turn - Item
Battle - Your Turn - Equip
Battle - Your Turn  - Rolling
Battle - Select Target - Action
Battle - Select Target - Items
Currently, the overall look of these screens have been created. They need to be transferred to this branch and functionality needs to be added when a table cell is selected. The characters on the select target action screen needs to be buttons that are only selected when double tapped. Need to be able to select a name from the stats menu for select target - item. Include cases for when the player is blind or an enemy is invisible.

**Comment by OddJerbb** [comment]
Merged to main
